trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'testconnection'
    repository: 'kubernetes'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'